package com.cuesina.ui;

import com.cuesina.models.Recipe;
import com.cuesina.services.RecipeManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;

/**
 * MainWindow - Main application window with dashboard
 * Displays recipe list and provides access to main features
 *
 * @author [Your Name]
 * @version 1.0
 */
public class MainWindow extends JFrame {

    private final RecipeManager recipeManager;
    // GUI Components (generated by GUI Designer)
    private JPanel mainPanel;
    private JPanel headerPanel;
    private JLabel titleLabel;
    private JLabel subtitleLabel;
    private JPanel contentPanel;
    private JPanel buttonPanel;
    private JButton makeDishesButton;
    private JButton findDishButton;
    private JPanel sidebarPanel;
    private JLabel sidebarTitleLabel;
    private JList<String> recipeList;
    // Additional components
    private DefaultListModel<String> recipeListModel;

    /**
     * Constructor - Initialize main window
     */
    public MainWindow() {
        recipeManager = RecipeManager.getInstance();

        setContentPane(mainPanel);
        setTitle("Cuesina - Personal Recipe Recommendation System");
        setSize(1200, 700);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        initializeComponents();
        setupButtonActions();
        setupKeyboardShortcuts();
        loadRecipes();
    }

    /**
     * Initialize UI components
     */
    private void initializeComponents() {
        // Setup recipe list
        recipeListModel = new DefaultListModel<>();
        recipeList.setModel(recipeListModel);
        recipeList.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        recipeList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        recipeList.setFixedCellHeight(50);
        recipeList.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

        // Make panels transparent
        contentPanel.setOpaque(false);
        buttonPanel.setOpaque(false);
        buttonPanel.setBorder(BorderFactory.createEmptyBorder(50, 20, 50, 20));

        // Style buttons
        makeDishesButton.setFocusPainted(false);
        makeDishesButton.setBorderPainted(false);
        findDishButton.setFocusPainted(false);
        findDishButton.setBorderPainted(false);

        // Add tooltips
        makeDishesButton.setToolTipText("Add a new recipe (Ctrl+N)");
        findDishButton.setToolTipText("Find recipes based on ingredients (Ctrl+F)");
        recipeList.setToolTipText("Click a recipe to view details");
    }

    /**
     * Setup button click handlers
     */
    private void setupButtonActions() {
        // Make Dishes button - opens add recipe dialog
        makeDishesButton.addActionListener(e -> {
            AddRecipeDialog dialog = new AddRecipeDialog(this);
            dialog.setVisible(true);
        });

        // Find a Dish button - opens recommendation dialog
        findDishButton.addActionListener(e -> {
            FindDishDialog dialog = new FindDishDialog(this);
            dialog.setVisible(true);
        });

        // Recipe list selection - opens recipe viewer
        recipeList.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && recipeList.getSelectedIndex() != -1) {
                openRecipeViewer(recipeList.getSelectedIndex());
            }
        });
    }

    /**
     * Setup keyboard shortcuts
     */
    private void setupKeyboardShortcuts() {
        // Ctrl+N - New Recipe
        KeyStroke ctrlN = KeyStroke.getKeyStroke(KeyEvent.VK_N, KeyEvent.CTRL_DOWN_MASK);
        mainPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(ctrlN, "newRecipe");
        mainPanel.getActionMap().put("newRecipe", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                AddRecipeDialog dialog = new AddRecipeDialog(MainWindow.this);
                dialog.setVisible(true);
            }
        });

        // Ctrl+F - Find Dish
        KeyStroke ctrlF = KeyStroke.getKeyStroke(KeyEvent.VK_F, KeyEvent.CTRL_DOWN_MASK);
        mainPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(ctrlF, "findDish");
        mainPanel.getActionMap().put("findDish", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FindDishDialog dialog = new FindDishDialog(MainWindow.this);
                dialog.setVisible(true);
            }
        });
    }

    /**
     * Load recipes from database into sidebar
     */
    private void loadRecipes() {
        try {
            recipeListModel.clear();
            List<Recipe> recipes = recipeManager.getAllRecipes();

            if (recipes.isEmpty()) {
                recipeListModel.addElement("<html><div style='padding:10px; text-align:center;'>" +
                        "<b>No recipes yet!</b><br>" +
                        "<span style='font-size:10px; color:gray;'>Click 'MAKE DISHES' to add your first recipe</span>" +
                        "</div></html>");
            } else {
                for (Recipe recipe : recipes) {
                    String displayText = String.format(
                            "<html><div style='padding: 5px;'>" +
                                    "<b style='font-size: 12px;'>%s</b><br>" +
                                    "<span style='font-size: 10px; color: gray;'>%d ingredients</span>" +
                                    "</div></html>",
                            recipe.getName(),
                            recipe.getIngredientCount()
                    );
                    recipeListModel.addElement(displayText);
                }
            }

        } catch (Exception e) {
            System.err.println("Error loading recipes: " + e.getMessage());
            e.printStackTrace();
            recipeListModel.addElement("Error loading recipes");
        }
    }

    /**
     * Open recipe viewer for selected recipe
     *
     * @param index Index of selected recipe
     */
    private void openRecipeViewer(int index) {
        try {
            List<Recipe> recipes = recipeManager.getAllRecipes();

            if (index >= 0 && index < recipes.size()) {
                Recipe selectedRecipe = recipes.get(index);
                ViewRecipeDialog dialog = new ViewRecipeDialog(this, selectedRecipe);
                dialog.setVisible(true);
            }

        } catch (Exception e) {
            System.err.println("Error opening recipe viewer: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error loading recipe details: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Refresh recipe list (called after add/edit/delete)
     */
    public void refreshRecipeList() {
        loadRecipes();
    }
}